RedHatInsights/insights-operator-utils

responses/responses.go, responses/responses_test.go
Work in progress. Need to discuss.
Re-created PR so its draft because WIP keyword doesnt work on GitHub
=> add unit tests

Makefile, golint.sh, govet.sh, test.sh
Fixes in shell scripts.
Done on CI already
=> Shell scripts fixes

responses/responses.go
Fixed typo, what else to say :)
\## Testing steps
N/A
=> (trivial) Fixed typo

responses/responses.go, responses/responses_test.go
Check for error values
Fixes #12 
Done on CI
=> Send error values

README.md
=> Added all remaining badges

responses/responses_test.go
Minor - added missing error check
Please see CI report
=> Added missing error check

responses/responses.go
=> Fixed typo

env/env_test.go
Unit tests for `env` sub-package.
Fixes #22 
It is done on CI
=> Unit tests for env

Makefile, ineffassign.sh
Configure ineffassign tool on CI
Fixes #13 
Run `./ineffassign.sh` or wait for CI to complete.
=> Add ineffassign tool

Makefile, env/env_test.go, goerrcheck.sh, responses/responses_test.go
Incorporate errorcheck tool into CI.
Everything should hopefully run on CI
=> Implement errcheck

README.md
Mention all checks in README.md
N/A
=> Mention all checks in README.md

PULL_REQUEST_TEMPLATE.md
Updated template to be compatible with other repositories
N/A
=> Updated template to be compatible with other repositories

gofmt.sh
Missing  license in `gofmt.sh`
- Minor change
N/A
=> Missing license in gofmt.sh

CONTRIBUTING.md, DoD.md, LICENSE, gofmt.sh, golint.sh, govet.sh
Proper (c) year in license file and other minor improvements that don't touch the actual code.
N/A
=> Proper c year in license

Makefile, README.md, abcgo.sh
Incorporate ABC metrics
Fixes #41 
It is possible to run `make abcgo` on CLI
=> Incorporate ABC metrics

responses/responses_test.go
Unit test for function `SendNotFound`
Fixes #45
=> Unit test for function SendNotFound

test.sh
Correct expansion done by `go list`
Fixes #43
=> Fix issue #43

check_coverage.sh, goconst.sh
Fixed `goconst.sh` and `check_coverage.sh` scripts a bit.
Fixes #47
=> Fix issue 47

collections/slices.go, collections/slices_test.go
Function StringInSlice will be used by several projects, so refactored out of Aggegator repository.
Fixes #50 
=> String in splice function

CODEOWNERS, responses/responses.go, responses/responses_test.go
SendServiceUnavailable response is to be used in aggregator 
Adds CODEOWNERS
Fixes #53 #55 
`make test`
=> add SendServiceUnavailable response

responses/responses.go, responses/responses_test.go
Added the possibility of feeding Send with a bytes array
Regular CI
=> Add Send with raw data

Makefile, docs/packages/collections/slices.html, docs/packages/collections/slices_test.html, docs/packages/env/env.html, docs/packages/env/env_test.html, docs/packages/responses/responses.html, docs/packages/responses/responses_test.html, docs/packages/tests/helpers/errors.html, docs/packages/tests/helpers/frisby.html, docs/packages/tests/helpers/strings.html, docs/packages/tests/helpers/timeout.html
Documentation in literate programming style
Fixes #59
=> Documentation in literate programming style

tests/helpers/http.go, tests/helpers/json.go
Fixes some bugs
- This change requires a documentation update
=> Fixed some bugs

tests/helpers/http.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> fixed a bug

docs/packages/http/http.html, docs/packages/http/metrics_middleware.html, docs/packages/http/router_utils.html, docs/packages/http/router_utils_test.html, docs/packages/metrics/metrics.html, docs/packages/metrics/metrics_test.html, docs/packages/tests/helpers/json.html, docs/packages/tests/helpers/micro_server.html, docs/packages/tests/helpers/serialization.html, docs/packages/types/auth.html, docs/packages/types/errors.html, docs/packages/types/pg_consts.html, docs/packages/types/types.html
Update of the docgo generated files to match the later changes on the repository
Regular CI
=> Updating godoc documentation

docs/index.md
Links to all generated documents
Fixes #60 
Will be visible on GitHub pages.
=> Links to all generated documents

abcgo.sh, goconst.sh, gocyclo.sh, goerrcheck.sh, golint.sh, gosec.sh, ineffassign.sh
There's no need to install already installed tools used on devel machines and on CI as well.
Fixes #73 #74 #75 #76 #77 #78 #79
These scripts are used on CI, so everything should be visible there.
=> Enhancements of CI scripts

docs/packages/http/http.html, docs/packages/http/http_test.html, docs/packages/tests/helpers/http.html, docs/packages/types/types.html, http/http.go, http/http_test.go
Minor fix to replace special characters that can be in an URL to its escaped versions
Fixes #81 
Regular CI
=> Fix bug with spaces in URLs for MakeURLToEndpoint

tests/helpers/http.go
For PR https://github.com/RedHatInsights/insights-results-aggregator/pull/947 needed single check function.
=> Added single rule check assert

docs/packages/tests/helpers/http.html
Updated generated documentation
N/A
=> Updated generated documentation

types/types.go
This structure is representing single hit for rule.
=> Added representing of single rule

docs/packages/types/types.html
Regenerate doc with new data types
N/A, will be visible on GitHub pages
=> Regenerate doc with new data types

README.md
Updated README.md -> fixed main branch name
Fixes #86
N/A
=> Updated README.md -> fixed main branch name

README.md
Badge with link to GitHub pages
Fixes #93 
N/A
=> Badge with link to GitHub pages

http/router_utils.go, types/errors.go
=> added-few-functions-to-router-utils

docs/packages/http/http.html, docs/packages/http/http_test.html, docs/packages/http/router_utils.html, docs/packages/http/router_utils_test.html, docs/packages/tests/helpers/http.html, docs/packages/tests/helpers/json.html, docs/packages/tests/helpers/micro_server.html, docs/packages/tests/helpers/serialization.html, docs/packages/types/auth.html, docs/packages/types/errors.html, docs/packages/types/types.html
Updated documentation + license
N/A
=> Updated documentation + license

http/router_utils.go, tests/helpers/strings.go, types/errors.go
`make style; and make test` and CI of course
=> Added a few functions

docs/packages/tests/helpers/strings.html
=> Updated doc

tests/helpers/http.go, types/errors.go, types/types.go
=> added-some-more-common-functions

go.mod, go.sum, http/openapi.go, http/openapi_test.go
=> filtering-openapi-debug-methods

tests/helpers/http.go, types/types.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
- This change requires a documentation update
- Benchmarks (no changes in the code)
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the …
=> some fixes

docs/generate_class_diagram.sh, docs/packages/tests/helpers/http.html, docs/packages/types/types.html
Updated missing generated docs
N/A
=> Updated missing generated docs

docs/packages/types/content.html, docs/packages/types/types.html
Another bulk of doc changes
N/A
=> Another bulk of doc changes

docs/generate_class_diagram.sh
Script to generate class diagram should reformat SVG
N/A
=> Script to generate class diagram should reformat SVG

types/content.go
=> made `has reason` field public

docs/packages/http/router_utils.html, docs/packages/http/router_utils_test.html, docs/packages/types/content.html, docs/packages/types/types.html, http/router_utils.go, http/router_utils_test.go, types/types.go
Cluster list handling code
N/A
=> Cluster list handling code

docs/packages/types/types.html, types/types.go
=> Cluster reports data type

tests/helpers/errors.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #90
- This change requires a documentation update
- Benchmarks (no changes in the code)
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing …
=> optional-message-for-fail-on-error

docs/packages/tests/helpers/errors.html
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
N/A
=> Another docs update

docs/packages/http/router_utils.html, http/router_utils.go
=> Handle empty request body

go.mod, go.sum
Updating cloudwatch after this PR https://github.com/RedHatInsights/cloudwatch/pull/4
- 
Just run it
=> Updated Cloudwatch to latest version

ineffassign.sh
Update for new ineffassign version
Fixes #138
N/A
=> Update for new ineffassign version

logger/logger_test.go
Fixed tests after https://github.com/RedHatInsights/insights-operator-utils/pull/137
just run tests
=> Fixed tests after Cloudwatch update

ineffassign.sh
Sync `ineffassign.sh` with other repositories
N/A
=> Sync ineffassign.sh with other repositories

docs/packages/types/types.html, types/types.go
=> Updated doc: version type

docs/packages/http/router_utils.html, docs/packages/logger/logger_test.html, http/router_utils.go
Minor problem in `go vet` output and updated docgo generated files
Regular CI
=> Fix govet warnings and update docs

docs/packages/tests/saramahelpers/mock_consumer_group_claim.html, docs/packages/tests/saramahelpers/mock_consumer_group_session.html, tests/saramahelpers/mock_consumer_group_claim.go, tests/saramahelpers/mock_consumer_group_session.go
Moving some sarama test helpers from aggregator to this repository
Regular CI
=> Adding sarama helpers

go.mod
Bump up golang client version
Fixes #163
- Update project dependencies
N/A ATM
=> Bump up golang client version

docs/packages/http/metrics_middleware_test.html, docs/packages/http/openapi.html, docs/packages/http/openapi_test.html, docs/packages/logger/configuration.html, docs/packages/logger/logger.html, docs/packages/logger/logger_test.html, docs/packages/tests/helpers/catchoutput.html, docs/packages/tests/helpers/catchoutput_test.html, docs/packages/tests/helpers/export_test.html, docs/packages/tests/helpers/helpers_test.html, docs/packages/tests/helpers/mock_t.html, docs/packages/tests/helpers/mock_t_test.html, docs/packages/tests/saramahelpers/mock_consumer_group_claim.html, docs/packages/tests/saramahelpers/mock_consumer_group_session.html, docs/packages/types/content.html, http/metrics_middleware_test.go, http/openapi.go, http/openapi_test.go, logger/configuration.go, logger/logger.go, logger/logger_test.go, tests/helpers/catchoutput.go, tests/helpers/catchoutput_test.go, tests/helpers/export_test.go, tests/helpers/helpers_test.go, tests/helpers/mock_t.go, tests/helpers/mock_t_test.go, tests/saramahelpers/mock_consumer_group_claim.go, tests/saramahelpers/mock_consumer_group_session.go, types/content.go
=> Missing doc pieces

CODEOWNERS
Adding last new hires to the code owners list
Regular CI
=> Adding Jiri and Juan to CODEOWNERS

types/content.go
Necessary for CCXDEV-4454
- This change requires a documentation update
make test
=> extend rule content structs because of different file lookup mechanism

types/types.go
Needed for: https://github.com/RedHatInsights/insights-results-aggregator-data/pull/158
Unfortunately we are using different structs in smart-proxy for testing for some reason.. We should unify it, but the task we have for it has low priority.
Tested alongside insights-results-aggregator-data and smart-proxy. passes
=> update structs used for testing purposes

types/types.go
Acknowledgement-related types
N/A
=> Acknowledgement-related types

parsers/date_test.go, parsers/rule.go, parsers/rule_test.go, types/types.go
=> Rule selector parser

CODEOWNERS
Please remove my user from CODEOWNERS.
=> Removed @quarckster from CODEOWNERS

types/types.go
New types - `DisabledRule` and `RuleToggle`
N/A
=> New types - `DisabledRule` and `RuleToggle`

types/types.go
New data type - `DisabledRuleReason`
N/A
=> New data type - `DisabledRuleReason`

types/types.go
New data type to store information about system-wide ack
Fixes #187
N/A
=> System-wide ack (rule disable) data type

go.mod, go.sum, types/content.go
updated impact field
Fixes CCXDEV-5613
None
=> update impact field

types/types.go
=> `RuleContentStatus` type

generators/rule.go, generators/rule_test.go, go.sum
TBUsed initially in smart-proxy and aggregator-data repos and probably more in the future
`make test`
=> Add generator for composite Rule ID

tests/helpers/mock_t.go
Removed `defer` - not needed there
=> Removed `defer` - not needed there

types/metrics.go
Added a type to use with `metrics/push` package.
=> add metrics configuration to types package

README.md
=> Add TLS to README

README.md, s3/copier.go, s3/copier_test.go, s3/deleter.go, s3/deleter_test.go, s3/downloader.go, s3/downloader_test.go, s3/helpers_test.go, s3/lister.go, s3/lister_test.go, s3/mocks/mock.go, s3/uploader.go, s3/uploader_test.go, s3/utils.go, s3/utils_test.go
This package will be used in many internal repositories.
Tested against real buckets.
=> Add s3 package

PULL_REQUEST_TEMPLATE.md
Pull request template update
Fixes #184
N/A
=> Pull request template update

http/openapi.go
Compatible `nosec` clause
Done on CI
=> Compatible `nosec` clause

gosec.sh
Install and use latest gosec on CI
Done on CI
=> Install and use latest gosec on CI

Makefile, README.md
New `cover` and `coverage` targets in `Makefile`
N/A
=> New `cover` and `coverage` targets in `Makefile`

logger/logger_test.go
`Log.println` unit test
Done on CI
=> `Log.println` unit test

go.mod, go.sum
Update `uuid` library to 1.3.0
Fixes #225
Done on CI
=> Update `uuid` library to 1.3.0

http/router_utils_test.go
Use `http.NoBody` instead of `nil`
Done on CI
=> Use `http.NoBody` instead of `nil`

go.mod, go.sum
Update `testify` to version 1.7.0
Fixes #224
Done on CI
=> Update `testify` to version 1.7.0

metrics/push/gateway_test.go, tests/helpers/helpers_test.go
Dont use `nil` as request body
Done on CI
=> Dont use `nil` as request body

http/router_utils.go, logger/logger.go, metrics/push/push.go, tests/helpers/http.go
Check for empty strings + other fixes
Done on CI
=> Check for empty strings + other fixes

env/env_test.go, http/openapi.go, tests/helpers/http.go, tests/helpers/micro_server.go
=> Combine parameters

tests/helpers/helpers_test.go
=> Use `io.NopCloser`

Makefile, s3/deleter.go, s3/deleter_test.go, s3/helpers_test.go, s3/lister.go, s3/mocks/copier.go, s3/mocks/deleter.go, s3/mocks/downloader.go, s3/mocks/lister.go, s3/mocks/mock.go, s3/mocks/uploader.go, s3/mocks/utils.go, types/legacy_types.go
Refactored and included a new function `DeleteObjects` that will be used in Parquet Factory.
Unit tests.
=> S3utils refactor

collections/slices.go, collections/slices_test.go, s3/mocks/lister.go, s3/mocks/utils.go
=> Refactored index function

Makefile, README.md
Include `before_commit` and `license` targets in `README.md`.
=> Add before_commit and license to README

logger/logger_test.go
Removed unused code
Done on CI
=> Removed unused code

go.sum, tests/helpers/rules.go
new param in function
Fixes CCXDEV-7859
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> new param in function

evaluator/evaluator.go, evaluator/evaluator_test.go, evaluator/shunting_yard.go, evaluator/stack.go, evaluator/token.go, evaluator_demo.go, gocyclo.sh
Evaluator + unit tests to have it almost 100% code covered
Done on CI I hope
=> Evaluator + unit tests to have it almost 100% code covered

evaluator/evaluator.go, evaluator/stack.go
Fix two problems in evaluator:
1. divide by zero
2. strict expression check
Done on CI
=> Fix two problems in evaluator - divide by zero + strict expression check

evaluator/evaluator.go, evaluator/evaluator_test.go
More test cases, the unary minus doesn't seem to work
Fixes: na
Please describe how the change was tested locally. If, for some reason, the testing was not done or not done fully, please describe what are the testing steps.
=> more test cases

Makefile, README.md, benchmark.sh, evaluator/benchmark_test.go
Evaluator benchmarks
- Benchmarks (no changes in the code)
Can be run from CLI
=> Evaluator benchmarks

go.mod, go.sum, migrations/errors.go, migrations/migrations.go
utils provide a pattern to perform database migrations  
Fixes # CCXDEV-8774
N/A
=> migration utils

http/http.go, http/http_test.go
Extend `httputils` module with some functions for creating requests in `ccx-notification-service`.
Run unit tests.
=> Add new functions to httputils module

.github/workflows/golangci-lint.yml, README.md
Setup GolangCI
Fixes #245
Done on CI
=> Setup GolangCI

README.md, evaluator/evaluator.go
=> Added missing Go doc

evaluator/shunting_yard.go
=> Removed commented code

parsers/date_test.go
Date items are not octal numbers
N/A
=> Date items are not octal numbers

evaluator/evaluator_test.go, evaluator/export_test.go
One hundred code coverage for `evaluator`
Done on CI
=> One hundred code coverage for evaluator

collections/slices_test.go, evaluator/evaluator_test.go, generators/rule_test.go, http/http_test.go
Improve unit tests a bit
Done on CI
=> Improve unit tests a bit

README.md, http/openapi_test.go
Unit tests for `CreateOpenAPIHander` function
Done on CI
=> Unit tests for CreateOpenAPIHander function

check_coverage.sh
Increase coverage threshold to 90%
- Other
Done on CI
=> Increase coverage threshold to 90%

tests/helpers/rules_test.go
Unit tests for function `helpers.CompareReportResponses`
Done on CI hopefully
=> Unit tests for function `helpers.CompareReportResponses`

tests/helpers/rules.go, tests/helpers/rules_test.go
Fix sorting reports
Done on CI
=> Fix sorting reports

check_coverage.sh
Increase coverage threshold to 95%
Done on CI
=> Increase coverage threshold to 95%

README.md, collections/slices.go, docs/index.md, docs/references.md, env/env.go, evaluator/evaluator.go, generators/rule.go, http/http.go, parsers/date.go, responses/responses.go, s3/s3util.go, tls/tls_config.go, types/types.go
=> Updated doc v1

goconst.sh
Colorful `goconst`
Can be seen on CI
=> Colorful `goconst`

CODEOWNERS, LICENSE, Makefile, collections/slices.go, env/env.go, evaluator/evaluator.go, generators/rule.go, gocyclo.sh, goerrcheck.sh, gofmt.sh, golint.sh, govet.sh, http/http.go, parsers/date.go, responses/responses.go, s3/s3util.go, shellcheck.sh, tls/tls_config.go, types/types.go
More minor fixes
- Other
Done on CI
=> More minor fixes

utils.go
Repository-level documentation to be displayed there:
https://pkg.go.dev/github.com/RedHatInsights/insights-operator-utils#section-documentation
N/A
=> Repository-level documentation

README.md, docs/index.md, formatters/formatters.go, formatters/formatters_test.go
Formatters package
Partially solves https://github.com/RedHatInsights/insights-results-smart-proxy/issues/640
Done on CI
=> Formatters package

tests/helpers/helpers.go, tests/saramahelpers/samarahelpers.go, tests/tests.go
Added remaining docstrings
N/A
=> Added remaining docstrings

tests/helpers/rules.go
Proper parameter name
Done on CI
=> Proper parameter name

responses/responses.go, types/errors.go
Add the type and function to respond with a 204 status code.
=> Add nocontent response

README.md
Go language badge
Fixes https://github.com/RedHatInsights/insights-operator-utils/issues/280
N/A
=> Go language badge

evaluator/evaluator_test.go
Simplify `evaluator_test` source.
=> Simplify evaluator test sources

logger/export_test.go, logger/logger.go, logger/logger_test.go
Unit test for `convertLogLevel` function
=> Unit test for `convertLogLevel` function

CODEOWNERS
Updated code owners list - removed Daniele
N/A
=> Updated code owners list - removed Daniele

types/errors_test.go
For some reason program code in `types` package was not covered by unit tests. Let's improve that.
To be run on CI.
=> Basic unit tests for `types` package

http/http.go
Import shadow fix
- Fix (non-breaking change which fixes an issue)
=> Import shadow fix

s3/copier_test.go
=> Refactoring: duplicated code

s3/deleter_test.go
=> Copier test refactoring #2

tests/helpers/rules_test.go
Refactoring: `RuleOnReport` constructor for tests
=> Refactoring: `RuleOnReport` constructor for tests

.github/workflows/gh-pages.yml, Makefile, docs/Gemfile, docs/_config.yml, docs/sources.tmpl.md, gen_sources_md.sh
Enhance literate documentation generation
N/A
=> Adding generated index for literate documentation

http/metrics_middleware.go, http/metrics_middleware_test.go, metrics/metrics.go, metrics/metrics_test.go
Log the endpoint in the `api_endpoints_requests` with the status code.
Locally.
=> [CCXDEV-9825] Log the endpoint in the api_endpoints_requests too

.github/workflows/gh-pages.yml, .github/workflows/gotests.yaml, .github/workflows/linters.yaml, go.mod
=> Update go version to 1.20

http/router_utils.go
Continuation of https://github.com/RedHatInsights/insights-operator-utils/pull/569
=> [CCXDEV-14053] Reduce error level messages

types/conversion.go, types/conversion_test.go, types/errors.go
Follow up of #582, introducing proper error type and handling
CI
=> Add OutOfRangeError and handle it properly
