RedHatInsights/insights-operator-utils

- responses/responses.go
Even though they actually send JSON.
Copying the message from JIRA why a nonoptimal solution is used.
@tisnik 
The best solution would be to set the Content-Type only once in the SendResponse function, since all the others call it. However, there is a [documented functionality](https://golang.org/src/net/http/server.go?s=2985:5848#L84) disallowing the modification of headers on a ResponseWriter once the WriteHeader function has been called.
With that in mind, the next best solution would be to add an extra argument to SendResponse - httpStatus int - and send the required status like that, reducing the functions to 1 line like this
```
func SendCreated(w http.ResponseWriter, data map[string]interface{}) {
SendResponse(w, data, http.StatusCreated)
}
```
However - the insights-operator-utils …
> Fix responses not having content-type json

- Makefile
- README.md
- goconst.sh
- gocyclo.sh
- ineffassign.sh
Setup `goconst` tool on CI + updating documentation a bit
Fixes #31 
It's done on CI or you can run the new `goconst.sh` script
> Goconst on CI

- responses/responses.go
- added SendNotFound func to the responses
- sorted by error code
After this is merged, I will implement the new function wherever we use the `Send(http.StatusNotFound...)`
n/a
> add SendNotFound response; sort responses by error code

- Makefile
- README.md
- gosec.sh
Incorporate `gosec` security issues checker into CI.
Fixes #40 
- Tests on CI
Run `make style`
> Incorporate gosec

- types/types.go
add Internal field to RuleWithContent and RuleContentResponse, I got my types.go confused a bit locally
Necessary for https://github.com/RedHatInsights/insights-results-smart-proxy/pull/85
`make test`
> add Internal field to RuleWithContent and RuleContentResponse

- docs/packages/logger/configuration.html
- docs/packages/logger/logger.html
- docs/packages/logger/logger_test.html
- go.mod
- go.sum
- logger/configuration.go
- logger/logger.go
- logger/logger_test.go
Moving CloudWatch logging from Insights Results Aggregator to this project in order to be used by the different services
All the external data pipeline services written in Go should log into Cloudwatch, in order to get their logs on Kibana. As we already have one implementation in Insights Results Aggregator, I'm going to copy the source code here in order to be reused by the rest of the services
Regular CI
> Cloudwatch logging as a library

- .github/workflows/release_workflow.yaml
Adding GitHub workflow in order to autogenerate the release when a new tag is pushed in the repository.
This PR doesn't affect to current files or documentation in the repository. It should work only when a new tag is pushed to the repository by anyone
> GitHub action to auto-generate release when tags are pushed

- types/types.go
Added SchemaVersion as a type in insights-operator-utils so we can use it in insights-results-aggregator and insights-results-aggregator-data repositories. This change is needed to fix https://github.com/RedHatInsights/insights-results-aggregator/issues/1091
> Add SchemaVersion type

- logger/logger.go
- logger/logger_test.go
`zerolog` allows to use `io.Writer` interface or `zerolog.LevelWriter`, that enables de implementation of the writer to handle the level of the message. In order to being able to use the later, a `zerolog.MultiLevelWriter` should be used instead of `io.Writer`
Regular CI
> Using MultiLevelWriter to enable clients to use LevelWriters

- docs/packages/logger/configuration.html
- docs/packages/logger/logger.html
- docs/packages/logger/logger_test.html
- go.mod
- go.sum
- logger/configuration.go
- logger/logger.go
- logger/logger_test.go
Adds support for using `kafkazerolog` writer in order to send log messages directly to a Kafka topic. Supports Kafka over SSL
Regular CI
> Adding support for using Kafka topic to send log messages

- docs/packages/logger/configuration.html
- docs/packages/logger/logger.html
- logger/configuration.go
- logger/logger.go
Update configuration for Kafka logging to allow use an string instead of integers
Regular CI
> Configure the log level using an string instead of integer

- go.mod
- go.sum
- types/content.go
Condition field has been deprecated from the provided rules. This commit removes the related field in the structure used for parsing the error key that contains it.
Not fully tested yet
> Remove condition field from rules' error key

- types/types.go
Change the cluster report struct to contain a `json.RawMessage` instead of a generic `interface{}`, making it possible to unmarshall the content of the report if needed.
This change could require changes in other repositories to use this functionality 
Regular CI
> Use RawMessage for ease message parsing

- types/types.go
Tule `RuleRating` struct will be used by Aggregator and Smart Proxy, so it needs its place in the types package
Regular CI
> Move RuleRating struct from aggregator to utils in order to be used by several projects

- tls/tls_config.go
- tls/tls_config_inter_test.go
I mocked the NewTLSConfig function so we can test all its parts. I also discovered a bug because I was checking `caCert` instead of `caCertPool` not to be `nil`.
`go test`.
> Mock NewTLSConfig tests so we can reach a 100% coverage

- http/router_utils.go
- http/router_utils_test.go
Added information about specific orgIDs to error message about organization permissions.
Fixes # 200
The test with the message has been modified and executed.
> Add info about orgIDs to message about organization permission error

- s3/lister.go
Found a typo. I was calling `ListBucket` function instead of `listWithDelimiter`. I found it when listing a folder with more than `maxKeys` subfolders.
> Fix typo in s3 lister

- go.mod
- go.sum
Update gomock to version 1.6.0
Fixes #226
Done on CI
> Update `gomock` to version 1.6.0

- http/router_utils.go
- http/router_utils_test.go
The UI will now include ".report" in the `rule_selector`parameter as is done with v1 endpoints. This will simplify queries associated with the recommendations found in the reports. In our v2 endpoints, we need to trim the `.report` in most of our endpoints.
Fixes [CCXDEV-7183](https://issues.redhat.com/browse/CCXDEV-7183)
- Added corresponding UTs
- Tested the function locally with aggregator and smart-proxy's affected endpoints
> Expect .report in rule_selector param (v2 endpoints)

- go.mod
- go.sum
Updated `insights-resutls-types` to 1.3.5
Done on CI
> Updated `insights-resutls-types` to 1.3.5

- http/openapi.go
I just found a little nice function `strings.EqualFold`, let's train to use it where appropriate.
Done on CI.
> Use `strings.EqualFold` for string comparison ignoring case

- go.mod
- go.sum
- tests/helpers/http.go
- tests/helpers/micro_server.go
- tests/helpers/rules.go
created a new function to compare two rules responses. It is impossible to compare with a constant response as the CreatedAt field is dynamically created with time.Now() value 
Fixes CCXDEV-7859
na
> added new test util function

- http/router_utils.go
Use `regexp.MatchString` instead of `regexp.Match`
Done on CI
> Use `regexp.MatchString` instead of `regexp.Match`

- .travis.yml
- go.mod
Bump-up Go version to 1.17
N/A
> Bump-up Go version to 1.17

- responses/responses.go
- responses/responses_test.go
204 responses doesn't allow to send any data in the body.
Unit tests.
> [CCXDEV-10330] Don't send any body for 204 responses

- clowder/clowder_test.go
- clowder/export_test.go
- clowder/kafka.go
- clowder/storage.go
- go.mod
- go.sum
- kafka/configuration.go
- kafka/configuration_test.go
- kafka/scram_client.go
- postgres/config.go
- Kafka broker configuration is common in multiple services, so let's handle it here and reuse it instead of having it in multiple places
- Same thing for updating our config with values loaded by Clowder
Fixes CCXDEV-12032 partially
- Added UTs
- Tested in notification-writer and aggregator by replacing insights-operator-utils dependency with the local clone
> [CCXDEV-12032] Add common Kafka configuration and clowder-related utilities

- clowder/clowder_test.go
- clowder/export_test.go
- clowder/kafka.go
- kafka/configuration.go
- kafka/configuration_test.go
- Support slice of BrokerConfiguration items so we can get the full KafkaBrokers config from clowder
- Differentiate kafka.BrokerConfig into BrokerConfigurations and BrokersConfig. This helps simplify and clarify what is used in which method, and will imply a slightly more complex refactor on the services' side.
Fixes CCXDEV-12328
- Updated UTs
- All the changes have been tested using the ccx-notification-writer with this version of ioutils (adapted the service's code and its UTs, and tried it locally)
> [CCXDEV-12328] Support for multiple Kafka broker addresses

- clowder/clowder_test.go
- clowder/export_test.go
- clowder/kafka.go
- kafka/configuration.go
- kafka/configuration_test.go
`MultiBrokerConfiguration` struct brings too many possible use cases and ways of handling kafka configuration on the table. Let's keep it simple.
Fixes CCXDEV-12328
CI
> Refactor KafkaBroker configuration to keep it simple

- kafka/configuration.go
Use `addresses` instead of `address` in `BrokerConfiguration, as the field is expected to be an array of strings.
N/A
> Expect adresses instead of address in toml config file

- kafka/configuration.go
- kafka/configuration_test.go
From Sarama documentation:
`The version field represents the version of Kafka that Sarama will assume it is running against. It defaults to the oldest supported stable version. Since Kafka provides backwards-compatibility, setting it to a version older than you have will not break anything, although it may prevent you from using the latest features. Setting it to a version greater than you are actually running may lead to random breakage.
`
Let's not hardcode it to a specific version
UT in ccx-notification-service that creates a producer was not passing due to this line, as the `Sarama.mockBroker` is not working properly with a list of addresses and this version. Now it does
> Do not set a fixed Kafka version in sarama config

- clowder/clowder_test.go
- clowder/kafka.go
- kafka/configuration.go
Handling the slice of string when loading the config from an environment variable requires additional code as Viper does not do it automatically. That code is complex, as it is based on assuming that a variable is loaded by Viper and has a concrete name. It's easier to simply pass the list of broker addresses as a string and split it.
Fixes CCXDEV-12461 partially
- Refactor (the refactored code is not yet used by any service)
- UTs
- Tested locally, and now the services can read the BROKER_ADDRESSES env var directly without additional code
> Handle Kafka Broker addresses as string instead of slice

- types/errors.go
Don't use `ERROR` level for all kind of HTTP error responses because it's overloading our Glitchtip instance causing plenty of duplicates. Let's use `WARN` instead, unless for unknown errors.
CI
> [CCXDEV-14053] Don't use ERROR level for all kind of HTTP error responses

- go.mod
- logger/logger.go
It looks like Sentry groups the errors following [this order](https://medium.com/@aleksandr.chistiakov/sentry-make-it-work-not-just-noisy-ebbfa9c40850):
- Stacktrace
- Exception
- Message
Even though we tried to make a lot of changes to the `log.Error()` logs using `Err` and avoiding `Msgf`, we still have duplicates. This is because the Stacktrace/Exception are still dynamic, so we need to make use of [custom fingerprints](https://docs.sentry.io/platforms/go/usage/sdk-fingerprinting/) to better group our errors.
We can tweak this function in the future in order to apply some more filtering on the events, like f.e grouping by just the first 10 characters of the error message.
> [CCXDEV-14052][CCXDEV-14098] Avoid duplicates when using Sentry/Glitchtip

- goerrcheck.sh
- http/router_utils.go
- ineffassign.sh
- migrations/errors.go
- types/conversion.go
- types/conversion_test.go
- Added a utility function for secure conversion between uint types.
- Make Go linters happier (not refactoring further as I don't know if there are any tests checking the status of the returned errors during parsing)
CI
> Add utility to convert from uint64 to uint32 securely

- .github/workflows/gotests.yaml
- .github/workflows/linters.yaml
- .github/workflows/shellcheck.yaml
- redis/redis.go
- redis/redis_test.go
Currently, the `CreateRedisClient` function does not use username for authentication to the Redis instance. However, Clowder provides username as well, so this PR adds it so we can authenticate properly.
NA
> [CCXDEV-14922] Add username arg to CreateRedisClient function
